package mak.onelinecoding.truthortruth

object Questions {

    val HAPPY_HOUR = arrayListOf(
        "Would you “take care” of a spider for me? What about a cockroach?",
        "What motto would you put on your famliy crest?",
        "What’s the most embarassing thing you’ve had to ask Google?",
        "When was the last time you laughed so hard you cried?",
        "Why do you put up with me?",
        "Describe a time you accidentally mortified your parents as a child.",
        "Tell me your favorite joke. If I laugh, I drink.",
        "If I could help you with one unpleasant task, what would it be?",
        "Pay me three sincere compliments.",
        "What’s the best compliment you’ve ever been given? (Everybody else answers.)",
        "What’s the most common thing people praise or compliment you for?",
        "What’s something you’re proud of that not many people know about?",
        "What bad habit have you kicked?",
        "Who here is the kindest? Tell us why—with lovely examples.",
        "Fill in the blank. Defend yourself: I don’t care if  is for kids, I will still love it until I die.",
        "Do you try to always be honest with me, or do you tell me “that haircut looks great”-level white lies to be nice?",
        "What’s the best zinger you’ve ever come up with on the fly? I know you remember it.",
        "What are the farthest lengths you’ve gone to to cheer someone up?",
        "What is your ideal name for a dog? A cat? Now pick any non-traditional pet and name it.",
        "What movie or TV character do I most remind you of?",
        "What song are you most ashamed to admit to me that you love? Reply in song.",
        "With what hilarious story about me do you regale people I do not know?",
        "What’s the the most courageous thing you’ve ever accomplished?",
        "Aside from “moist”, what word can’t you stand the sound of?",
        "Am I better or worse off when I am caffeinated?",
        "Name a dream of yours that you’ve made come true.",
        "What is your happiest memory from when you were a single-digit-aged child?",
        "When’s the exact moment you knew we were on the same wavelength?",
        "What’s a situation that is always improved by my presence?",
        "If you had synesthesia, what color would I make you feel?",
        "Who would play me in the Oscar-winning film about my life?",
        "How have I helped you the most?",
        "Fill in the blank. Defend yourself: I don’t care if  is for kids, I will still love it until I die.",
        "Do you try to always be honest with me, or do you tell me “that haircut looks great”-level white lies to be nice?",
        "What’s the most considerate present you’ve ever received? Given?",
        "If dogs and their owners are supposed to have matching personalities, what type of dog should I get?",
        "What’s the title of your autobiography? Extra imaginary points if it includes a colon and a subtitle.",
        "What’s your favorite memory of our relationship?",
        "What snack do you find the most comfort in consuming?",
        "If you could have any body part of mine (for aesthetic, not medical, reasons), what would it be?",
        "What is something you love about me that other people don’t understand at all?",
        "If you could plan the perfect night with all of your friends, what would it entail?",
        "What movie or TV quote hits a little too close to home?",
        "Would you give me one of your kidneys?",
        "What positive impact do you think you have on other people?",
        "What would you entrust me with above anyone else?",
        "What board game are you positive you could destroy us all at?",
        "What’s something I’m selfconscious about that you think I should stop stressing out over?",
        "Describe the dream vacation you haven’t gotten to take. Then tell me how you can make it happen in five years or less.",
        "What’s your ultimate Sunday look like? Your ultimate sundae?",
        "What dish do you slay in the kitchen every time you make it?",
        "What are you rooting for me to achieve?",
        "What author’s body of work do you wish you were actually responsible for?",
        "If there were no barriers to entry, what job do you think you’d be amazing at?",
        "If you could instantly gain any skill, what would it be?",
        "Out of all of us, whose eyes would you like to see the world through for a day?",
        "We’re binging tonight! Pick the show and the snack.",
        "What song reminds you of me whenever you hear it?",
        "Would you ever see a band in concert that you hated just to make me happy? Have you?",
        "When do you think you peaked?",
        "On what topic could you be an expert TV talking head?",
        "Show me the funniest thing on the internet under 30 seconds long. If I laugh, I drink.",
        "If I were a perfume or cologne, what would my top, heart, and base notes be?",
        "Do you ever just let me win?",
        "What best represents me as a friend: a weighted blanket, a spin class, or a wine tasting?",
        "We’re starting a business. What venture would we be most successful at as a pair?",
        "What’s the most kickass you’ve ever felt?",
        "If we formed a gang, what would the name of our posse be?",
        "What’s the most fun you’ve ever had with strangers? Tell us the story.",
        "What do you wish you were as good at as me?",
        "What is something you know you’ll accomplish, no matter how many people tell you you can’t?",
        "If someone did me wrong, would you (a) comfort me, (b) distract me, or (c) get revenge for me?",
        "What makes you so much fun?",
        "If you could live anyone else’s life, whose would it be?",
        "Describe an act of petty protest you waged at work or school.",
        "What’s one thing you can start doing to put more beauty back into the world?",
        "What’s something that completely changed you when you encountered it for the first time?",
        "Do you ever pity-laugh at my jokes, even if you don’t think they’re funny?",
        "How many seconds is the ideal hug? Should we all test your hypothesis?",
        "What is the most comforting sound in the world?",
        "What discontinued item would you give anything to bring back?",
        "Would you trust me to pierce your ear, 80’s-sleepover style?",
        "I’m going to have permanent art deposited into my skin with needles. Pick a design for me. Bonus points if you draw it.",
        "What’s the biggest fear you’ve overcome?",
        "What smell takes you back to childhood?",
        "Do you brag about me to other people? What do you say?",
        "You suddenly become wealthy beyond the dreams of avarice.  What do you do with the rest of your life?",
        "What’s the weirdest compliment you’ve ever gotten?",
        "What would be your cheesy, 20-second, game-showcontestant anecdote?",
        "If I couldn’t reach an itch, would you do me a solid and scratch it?",
        "What’s guaranteed to hit you right in the feels?",
        "If you were a Care Bear, what would be on your belly?",
        "What’s the hold music for your brain?",
        "Liking what piece of pop culture gets someone your automatic stamp of approval?",
        "What’s the strangest nickname you’ve ever been given?",
        "Of all the things we do together, what is the best thing we do together?",
        "We’re road tripping through the middle of nowhere.  Do you have me drive or navigate?",
        "What was your first impression of me? Has it turned out to be the case?",
        "You get to travel back in time to warn me about one thing. What would it be?",
        "If we were flying somewhere together, who would volunteer to sit in the middle seat?",
        "What did you think you would hate, but ended up loving?",
        "What album have you spun the most times? Be honest. You can consult your music apps for verification.",
        "What do you secretly think I’d be amazing at?",
        "Who here is most likely to believe in supernatural, occult, or mystical stuff?",
        "Tell me about a disagreement we had—and how we resolved it. Has it made us stronger?",
        "What is your greatest stylerelated regret as an adult? Have you glo’d up since?"
    )


    val ON_THE_ROCKS = arrayListOf(
        "Describe the first time we met. What was your honest first impression of me?",
        "What’s the worst thing you’ve ever had to do at work or school? How’d you handle it?",
        "Do your best (or worst) impersonation of me. I promise to clap appreciatively.",
        "If I didn’t have my current job, what do you see me doing?",
        "What’s something I do that you hate?",
        "Describe your first real kiss. Then describe your last kiss.",
        "Describe your worst bathroom-related disaster.",
        "Have you ever been fired? If so, what for? If not, why not?",
        "What’s something you think people should appreciate more about you?",
        "What movie title describes your last relationship?",
        "What are your vices? Have they gotten better or worse over time?",
        "What’s something you miss about your last serious ex?",
        "Do you think you are happier—or sadder—than the average person? Why?",
        "When was the last time you thought you might die? What made you feel that way?",
        "Am I friends with anyone you can’t fully endorse? Is there anything you think I should consider about them?",
        "How are we right for each other romantically? Certainly you can think of at least one way we’re compatible.",
        "What was your most embarrassing moment that transpired in public? Let’s all relive it!",
        "What’s the worst date you’ve ever been on? Tell us all the juicy deets.",
        "Have you ever done something you’re not proud of for money? (Outside of an official job.)",
        "If you discover you’ll die today, what will be your biggest regret?",
        "Your Google history has been made public. Which search is the hardest to explain?",
        "What are you anxious about? Can we reassure you?",
        "If you had to eat one delectable part of my delicious body, what part would you choose?",
        "What’s my greatest physical asset? Don’t be shy.",
        "What’s something about your personal hygiene that you could be more rigorous about?",
        "How often do you think about your own death? How, and when, do you suspect it will happen?",
        "What’s something that’s definitely not my problem, but somehow always becomes my problem?",
        "Tell us about a time you got more wasted than was advisable.",
        "If you were to kill me, how would you do it?",
        "When was the last time you thought you might die? What made you feel that way?",
        "Am I friends with anyone you can’t fully endorse? Is there anything you think I should consider about them?",
        "How are we right for each other romantically? Certainly you can think of at least one way we’re compatible.",
        "What was your most embarrassing moment that transpired in public? Let’s all relive it!",
        "What’s something you’ve always done—and only realized as an adult that it was weird?",
        "What would you never, ever want my help with?",
        "How would Childhood You describe you now? Would that kid like you?",
        "If we were dying of thirst, how would we ration the last bottle of water between all of us here?",
        "How long did it take you to get over your last ex? What did you do to get over it? Are you actually over it?",
        "If I killed somebody, would you help me cover it up?",
        "Tell us about your last breakup talk. Who said what? Anything you wish you’d said?",
        "What’s the weirdest way you’ve ever earned money? How much did you get?",
        "Do you think you are more or less attractive than the average person? Why?",
        "What’s an offense you’ve committed that could get you fired from work?",
        "What’s the worst thing you’ve done in a relationship?",
        "If we were to meet for the first time today, would we become friends?",
        "Was your childhood happier than the average person’s?",
        "Have you ever dated a friend’s ex? Ever wanted to?",
        "Do you think you’re healthier, or more fit, than most people?",
        "You and I are dating. What’s going to break us up?",
        "What type of person have you always wanted to date, but never had the chance?",
        "What are your insecurities? How do they manifest in your day-to-day life?",
        "Have you ever had a pregnancy scare?",
        "Write me a new dating app bio in three sentences or less.",
        "Have you ever been in love? How do you know?",
        "Will we be friends in ten years?",
        "How are we wrong for each other romantically?",
        "What did you get in major trouble for doing as a kid, and did you ever learn your lesson?",
        "What album title describes our relationship? What is our soundtrack?",
        "Our minds have traded bodies. What’s the first thing you’re going to do in my body?",
        "Is there something that’s difficult to talk about amongst any of us here? Should we clear the air right now?",
        "Of the people here, who is overdue for some kind words? Let’s offer some good vibes now.",
        "Tell us about a secret you had to keep from your loved ones.",
        "Describe me in three words.",
        "When was the last time you cried? What happened? Do you need a hug?",
        "Do you think I have a more dominant or more submissive personality? Do you have any examples?",
        "How comfortable are we with one another? What things would make us uncomfortable?",
        "Do you think I care more or less about my reputation than most people?",
        "Have you ever had a discovery about your parents now that you’ve grown up?",
        "What is your worst coping mechanism? Defense mechanism?",
        "Is there something that’s difficult to talk about amongst any of us here? Should we clear the air right now?",
        "Of the people here, who is overdue for some kind words? Let’s offer some good vibes now.",
        "What’s the meanest thing you’ve seen me do?",
        "Is there a limit to what you would do for the right amount of money?",
        "Do you think you’re more prone to addiction than other people? Either way, how do you know?",
        "Describe my perfect life partner. Have I been on the right track to find this person?",
        "When was the last time you spoke to an ex? What was it about? Was there any tension?",
        "If I were a chain restaurant, which one would I be and why?",
        "Have you ever talked about me behind my back? If yes, what did you say?",
        "If someone offered you $10,000 to never talk to me again, would you?",
        "Have you broken any bones? What happened? Did you hear the crack?",
        "What’s a time when you let a problem go on for too long before you addressed it?",
        "Someone who’s never met me asks you what I’m like. How do you answer?",
        "What’s something you think people should never joke about?",
        "Tell us about the one that got away.",
        "When was the last time you lost your cool? What happened? How do you feel about it now?",
        "What’s something you’re still self-conscious about? Are you working on it?",
        "If you found out I’d been embezzling from work, would you rat me out?",
        "Assuming you were single, what would it take for you to get back together with your last ex?",
        "Have I ever told you a secret that you’ve let slip to a third party?",
        "Describe a time when you really disappointed someone. Did you ever earn back their trust?",
        "Who’s the smartest person here? Give us examples.",
        "Describe a way I’ve impacted your life—but may not know about.",
        "What’s a grand gesture you tried to save or repair a relationship?",
        "Tell us about a time you lied to your parents. Did they ever find out?",
        "Tell us about a time you were shot down romantically.",
        "Have you ever caught me in a lie? Did you confront me about it? Why or why not?",
        "Tell us about a time you shot someone down romantically.",
        "What is something you’re struggling with that we don’t know about?",
        "If I listed you as my job reference, what would you say about me? Would it all be true?",
        "Help me with my ten-year plan. Describe my ideal job, income, relationship status, and attitude ten years from now.",
        "What’s your most expensive mistake?",
        "Do you have any scars you want to show us? Pick one and tell us the story behind how you got it.",
        "When was the last time you lied to me? What was the lie?",
        "How many kids is too many kids? How many will you have?",
        "Of the people here, who do you think makes the most money? What makes you think so?",
        "What would we do on our first date? (If asking partners or exes: What did you do on your first date?)",
        "Have you ever pooped yourself as an adult?",
        "What animal am I most like? Describe how this species and I are similar.",
        "Do any of your friends not like me?"
    )

    val EXTRA_DIRTY = arrayListOf(
        "Have you ever had a threesome? Would you?",
        "Tell us about an awkward or inappropriate sex dream you’ve had. Was anyone here involved?",
        "Give us a passionate example of your dirty talk.",
        "Would you ever knowingly enter into an open relationship? What rules are required to keep the peace?",
        "When was the last time you were tested for a sexually transmitted infection? What were the results?",
        "Have I ever popped into your head while you were masturbating? Will it happen now that we’ve asked the question?",
        "Who do you think has had more sexual partners, you or me?",
        "What’s the messiest thing you’ve ever done sexually?",
        "What was your best orgasm? Was it with yourself, or someone else?",
        "If we were stuck on a desert island, would we become lovers?",
        "Describe your first time having sex. Include every cringey detail.",
        "How many people have you hooked up with off dating apps?",
        "Where’s the strangest place you’ve had sex?",
        "What’s the sex skill you’re most proud of?",
        "Have you ever done butt stuff? If not, would you like to? (Everybody else answers.)",
        "Describe your sex life with a movie title, and tell us your reasoning.",
        "When was the last time you were tested for a sexually transmitted infection? What were the results?",
        "Have I ever popped into your head while you were masturbating? Will it happen now that we’ve asked the question?",
        "Have you ever been caught masturbating or having sex?",
        "Have you ever cheated on anyone? What were the circumstances?",
        "Have you ever had a one-night stand?",
        "Who do you think will have more sexual partners by the time we die, you or me?",
        "Who here would have the best sexual chemistry with me? Based upon what evidence?",
        "What’s something you wish your ex would have done sexually, but didn’t?",
        "Have I gotten sexier since you’ve known me?",
        "If I cheat on my partner, is it absolutely essential that I tell them? Why or why not?",
        "Have you ever walked in on your parents doing that thing that grownups do when they love each other very much?",
        "What was your most shame-filled orgasm?",
        "True or false: sometimes it’s okay to have unprotected sex. Explain your reasoning.",
        "Have you ever had sex with someone who was already in a committed relationship?",
        "If I had a hot brother/sister, would you let them seduce you?",
        "Have you ever slid into someone’s DMs? Any techniques you want to share?",
        "Assuming we were both single, would you date me?",
        "Have you ever feared for your life or safety while drinking or on drugs? Take us to the scene.",
        "How often are you intoxicated when you have sex? How often are you sober? What’s the difference?",
        "Do you find me physically attractive? What if I bat my eyelashes like this?",
        "What is your favorite sexual position and why?",
        "When was the last time you masturbated?",
        "What’s a sexual thing you’ve never been able to try, but wish you could?",
        "What’s your opinion of open relationships? What’s your experience with monogamy?",
        "Have you ever served food or other edibles in an erotic context? How did it go?",
        "What would it take for us to have sex?",
        "What’s a sexual thing you gave a good try, but just couldn’t get into?",
        "Name the person here you’d most like to hook up with (but haven’t).",
        "What would it take for you to sleep with someone you’re not physically attracted to?",
        "If I had a hot mom/dad, would you let them seduce you?",
        "What’s the last inanimate object you put inside yourself or another person?",
        "Do you have nude images of anyone that I know on your phone right now?",
        "How open are you about your most intimate fantasies with your partner(s)?",
        "If your sex life was a pie chart, what portion of it would be: satisfactory, unsatisfactory, and mind-blowing?",
        "Describe your sex life with a song title.",
        "Are you more sexperimental, or less sexperimental, than the average person?",
        "How much money would a voyeuristic billionaire have to pay us for us to have sex in his velvet blimp?",
        "What’s your most complimented anatomical feature (as described by your lovers?)",
        "How open are you about your most intimate fantasies with your partner(s)?",
        "If your sex life was a pie chart, what portion of it would be: satisfactory, unsatisfactory, and mind-blowing?",
        "Who was the last person (besides your partner or your kids) whose junk you’ve seen?",
        "True or false: great sex requires a connection beyond physical attraction. Explain your thinking.",
        "Tell us about the first time you ever saw porn.",
        "True or false: great sex requires lube. State your case with first-hand evidence.",
        "Would you be (or have you been) a “guest star” in another couple’s bedroom?",
        "Describe the perfect foreplay: what activities, and for how long?",
        "The various sex juices. Sometimes they get on clothes. Tell us about when it happened to you.",
        "Have you ever sent nudes? How do you compose, frame, and light these images?",
        "Have you ever been injured while having sex?",
        "Have you ever paid for sex? Even if you haven’t, is there anything inherently problematic about it?",
        "What do you think is your most unique sexual interest?",
        "Who was the last person (besides your partner or your doctor) who’s seen your junk?",
        "Have you ever cried after—or during—sex?",
        "Do you have an age ceiling for a one-night stand?",
        "Have you ever had to contact past partners for... public health reasons?",
        "If we were in a porn together, what category would it be filed under?",
        "What’s the weirdest porn that you’ve ever clicked on?",
        "What’s the maximum number of people you’d be interested in having sex with at once?",
        "Looking for a weird but true story about an inappropriate boner.",
        "Have you ever found yourself wearing somebody else’s underwear?",
        "Who’s had more sex, you or your parents?",
        "Quick! Name your favorite porn star. And tell us about all the wonderful qualities that make them special.",
        "What’s the most surprising discovery you’ve made about your own body?",
        "When was the last time you had unprotected sex? Did it ever cross your mind?",
        "If a studio were to make a porn specifically for you, tailored to your specific tastes, what would it be like?",
        "How did your parents talk to you about sex?",
        "Inadvertent nudity. Tell us about when it happened to you.",
        "How would your partner (or your latest ex) describe your sex life with a movie title?",
        "What will be the sexy nickname they give you when you live at the oldfolks’ home?",
        "Have you ever been sexual on camera? Would you want to?",
        "You can send a message back in time to your teenage self about sex. What advice will you impart?",
        "Who here is the most likely to star in an adult film? Who here is the most likely to make and direct porn?",
        "What sex-related word are you not sure how to pronounce?",
        "What’s the kinkiest thing you’ve asked someone else to do?",
        "If you can abstain from sex and masturbation for one full year, you’ll win $27,000 and a nice used car. Will you make it?",
        "Are you a good kisser? How do you know?",
        "You can send a message back in time to your teenage self about sex. What advice will you impart?",
        "Who here is the most likely to star in an adult film? Who here is the most likely to make and direct porn?",
        "What did you observe from porn that you later realized was unrealistic? How’d you make this discovery?",
        "Imagine we’re your future (or current) children. How do you present the birdsand-the-bees talk to us?",
        "What scared you the most about sex as you were coming of age?",
        "Do you see yourself committing to one sexual partner for the rest of your life?",
        "What’s the kinkiest thing you were ever asked to do, but you declined instead?",
        "Are you loud during sex? Demonstrate with a dramatic interpretation of your signature sex sounds.",
        "Tell us about a time in which a romantic partner just didn’t understand how to do a certain sex thing.",
        "Do you have recurring fantasies that kind of trouble you, or surprise you? What are they?",
        "Do you think you have more or less sex than your next-door neighbors?",
        "Are you more of a top, a bottom, or versatile? Or do these labels not apply to you?",
        "Have you ever had sexy times in public?",
        "Describe the present state of your pubic hair.",
        "How would you describe your nipples to a blind person?",
        "When it comes to your sexual orientation, have you ever considered experimenting?",
        "Have you ever paid for porn? If so—how much money is in your spank bank budget?",
        "Do you know where your G-spot is? Are you sure?",
        "List all the illicit drugs you’ve tried. What more would you like to try?",
        "How confident are you in your oral sex skills? How do you know?"
    )


    val LAST_CALL = arrayListOf(
        "Do you think I’m more or less honest than you are?",
        "Do you ever put me down to make yourself feel better?",
        "Have you ever broken off plans with me to be with someone else?",
        "Who is in control in our relationship?",
        "What’s a fundamental difference between us, and will we ever resolve it?",
        "Do you think I’ll ever do anything worth being remembered by society?",
        "Where are we, and what are we doing, in ten years? Have we honestly improved each other’s lives?",
        "Have you ever harassed someone online? Do you think they deserved it? (Everybody else answers.)",
        "Does our relationship bring out the best in you? In me? If not, why?",
        "What’s something you resent about me?",
        "Describe a time you lost a little bit of respect for me.",
        "Describe three ways to improve my physical appearance and general attractiveness.",
        "What percentage of the time do you think I’m completely full of shit?",
        "Do you even remotely care what I think of you?",
        "If someone was interested in dating me, what thing about me would you tell them to change their mind?",
        "What have I ruined for you?",
        "What problem do I think I’m successfully hiding from everyone, but is actually completely obvious?",
        "Do you see us as equals?",
        "Do you think I’m good parent material?",
        "What thing do I love that you absolutely hate?",
        "What negative thing have I said about you that’s haunted you forever?",
        "What one change could I make that would vastly improve who I am as a person?",
        "What do you wish I’d just shut up about?",
        "Do I often seem like I’m being fake?",
        "What ethical boundaries are you happy to cross?",
        "Am I too picky? Too petty? Too selfish?",
        "Have you ever considered ending our relationship? Why?",
        "What’s the most amount of money you would lend me?",
        "Do you ever think I need to cut back on drinking or drugs?",
        "What’s the most needlessly mean thing you’ve ever heard me say about someone else?",
        "Have I ever done anything you think should have gotten me shitcanned?",
        "Are there certain situations with me you avoid on purpose?",
        "What’s the most egregious lie you’ve ever told me?",
        "Do you think I’m too clingy or demand too much attention?",
        "What personal demon are you in denial of?",
        "Do you think I’m continuing to grow, or is this the best I’ll ever be as a person?",
        "Are you sometimes embarrassed to be seen with me? Why?",
        "What do I never seem to understand about you?",
        "Do you think I have overachieved or underachieved?",
        "What will you never understand about me?",
        "What advice do I need but don’t want to hear?",
        "Do you think I’m capable of doing something you could never forgive me for?",
        "Name one thing I do that disgusts you.",
        "How have I disappointed you?",
        "Have you ever hurt someone on purpose?",
        "What do you think I need to just let go of?",
        "Name a time you wished we weren’t friends.",
        "Who’s someone we know that you wish I was more like and why?",
        "Do you ever feel like I’m holding you back?",
        "If I was in a relationship with someone you hated, would you tell me?",
        "Is there anything about me that creeps you out?",
        "Would you hire me?",
        "Do you have any secrets you keep from me and me only?",
        "Is there an expiration date on our relationship?",
        "What do I think I’m great at, but am actually terrible at?",
        "Have you ever been genuinely scared of me?",
        "What’s the most serious crime you’ve ever committed?",
        "What is (or would be) the worst thing about having me as a travel companion?",
        "Have I often struck you as immature or unable to take care of myself?",
        "Do you think I sometimes takes advantage of other people?",
        "What’s the worst thought you’ve ever had that you’ve never shared with anyone?",
        "Do you think I’m a bully?",
        "What’s the bitchiest thing you’ve ever said about me behind my back?",
        "Name a time you could have helped someone, but didn’t bother.",
        "What’s the most selfish thing you’ve ever done?",
        "What’s stupidest thing you’ve ever heard me say?",
        "What’s an offensive opinion you will never let go of?",
        "Do you think you’re better than me?",
        "If you do something you know is wrong, but don’t get caught, do you keep doing it?",
        "What’s the longest period of time you could spend with me before never wanting to see me again?",
        "Have you ever stolen anything from me?",
        "What’s the weirdest thing about me?",
        "Do you sometimes lie about being busy if you don’t want to deal with me?",
        "Would you trust me alone with your kids for more than a couple hours?",
        "Do you ever warn people about me before they meet me?",
        "Do you ever have to fake empathy?",
        "If I died tomorrow, what regrets would you have about our relationship?",
        "Have you ever knowingly let me embarrass myself, even if you could have stopped it?",
        "Have you ever ghosted someone you were close with?",
        "What’s the most annoying thing I do without realizing it?",
        "What am I the most ignorant about?",
        "Do you ever think I stir up drama because I enjoy it?",
        "What’s something you know would make you a better person, but you just don’t want to do it?",
        "Have you ever stabbed someone in the back or actively plotted against them?",
        "Is this the best I’ve looked since you’ve known me?",
        "What’s the worst thing you’ve ever done to an animal?",
        "How have I changed for the worse since we’ve met?",
        "What’s the most unreasonable thing you’ve ever completely lost your shit over?",
        "What’s the most terrible thing you’ve ever done for money?",
        "How have you dishonored your parents?",
        "Have you ever intentionally scammed someone or misled them for personal gain?",
        "If someone important to you said they’d stop seeing you unless you stopped seeing me, would you?",
        "Name a time you thought I was weak.",
        "When was the last time you were out of control?",
        "In what ways have you used me?",
        "Have you ever had to apologize to someone for my behavior?",
        "When have you let your pride get in the way of doing the right thing?",
        "Have you ever forced someone to do something against their will?",
        "Have you ever pretended to be someone else on the internet?",
        "Would your life be any worse if we had never met?",
        "Have you ever lied on a resume?",
        "What have you done while intoxicated that you wish you could take back?",
        "What’s the angriest you’ve ever been at me?",
        "If we lived across the country from each other, do you think we’d lose touch?"
    )
}
